---
# This Playbook would deploy following roles.
- hosts: all_hosts
  roles:
  - { role: 'reboot', become: yes, tags: 'reboot' }
  - { role: minimize_access, become: yes, tags: 'Changes' }
  - { role: rhosts, tags: 'security'}
  - { role: apt, tags: 'security'}
